# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipshift < Formula
  desc ""
  homepage "https://github.com/getclipshift/clipshift"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/getclipshift/clipshift/releases/download/v0.1.0/clipshift_0.1.0_darwin_arm64.tar.gz"
      sha256 "3ef2f2bbaf412780d9dd7a3641b8754e63ebfe526006c5bf738f13f613194a9a"

      def install
        bin.install "clipshift"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/getclipshift/clipshift/releases/download/v0.1.0/clipshift_0.1.0_darwin_amd64.tar.gz"
      sha256 "8fce441b6b8659ccf48303937d96787fb5d06214e9588f5fa9d129e25e33c6ef"

      def install
        bin.install "clipshift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/getclipshift/clipshift/releases/download/v0.1.0/clipshift_0.1.0_linux_amd64.tar.gz"
      sha256 "a274d10948d1af28e3e176b732e9805aa3882246577fd6d4e24d9dff3213ac42"

      def install
        bin.install "clipshift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getclipshift/clipshift/releases/download/v0.1.0/clipshift_0.1.0_linux_arm64.tar.gz"
      sha256 "798ce558a4d6aceffaf1a663d097ed01a8e367669b93d62dcb3abe0632ebafaa"

      def install
        bin.install "clipshift"
      end
    end
  end

  test do
    system "#{bin}/clipshift"
  end
end
